---
- name: install etcd
  shell: |
    tempdir=$(mktemp -d)
    wget -qO $tempdir/etcd.tar.gz https://github.com/etcd-io/etcd/releases/download/{{etcd_version}}/etcd-{{etcd_version}}-linux-amd64.tar.gz
    tar xzf $tempdir/etcd.tar.gz --strip-components=1 -C "$tempdir"
    mv $tempdir/etcd /usr/local/bin
    mv $tempdir/etcdctl /usr/local/bin
  args:
    creates: /usr/local/bin/etcdctl
  register: result

- name: install service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
  register: etcd_conf

- name: reload daemon
  systemd:
    daemon_reload: yes
  when: etcd_conf.changed

- name: restart etcd
  systemd:
    name: etcd.service
    state: restarted
  when: etcd_conf.changed

- name: start etcd
  systemd:
    name: etcd.service
    state: started
    enabled: yes
